BT_ENVIRONMENT='sandbox'
BT_MERCHANT_ID='your braintree merchant id'
BT_PUBLIC_KEY='your braintree public key'
BT_PRIVATE_KEY='your braintree private key'


place this in your config i.e config/application.yml